jobs:
- name: docker-build
  plan:
  - in_parallel:
    - get: pullrequest-resource
      trigger: true
  - params:
      build: pullrequest-resource
    put: image
  serial: true
resources:
- check_every: 10s
  name: pullrequest-resource
  source:
    branch: master
    password: ((github-password))
    uri: https://github.com/eroad/pullrequest-resource.git
    username: ((github-username))
  type: git
- name: image
  source:
    aws_access_key_id: ((aws-access-key))
    aws_secret_access_key: ((aws-secret-key))
    repository: 212136148154.dkr.ecr.ap-southeast-2.amazonaws.com/ci/pr
  type: docker-image
